"use client";
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {ArrowRight,Check,FileCheck2,Scale,ShieldCheck} from "lucide-react";
import {Header} from "@/components/Header";
import {ContractTotals,Enrollment} from "@/lib/types";
import {formatGen} from "@/lib/amount";
import {configuredAddress,connectWallet,readContract} from "@/lib/genlayer";

export default function Home(){
 const[account,setAccount]=useState("");const[isRefreshing,setIsRefreshing]=useState(false);const[totals,setTotals]=useState<ContractTotals>({total_received:0,total_held:0,total_paid_to_organizers:0,total_refunded_to_students:0});const[counts,setCounts]=useState({offering_count:0,enrollment_count:0});const[latestEnrollment,setLatestEnrollment]=useState<Enrollment|null>(null);const[syncOk,setSyncOk]=useState(false);const activeAddress=configuredAddress();
 const fetchState=useCallback(async()=>{if(!activeAddress||activeAddress==="0x0000000000000000000000000000000000000000")return;setIsRefreshing(true);try{const[c,t]=await Promise.all([readContract("get_counts"),readContract("get_totals")]);setSyncOk(c.success&&t.success);if(c.success&&c.data)setCounts(c.data as typeof counts);if(t.success&&t.data)setTotals(t.data as ContractTotals);const countData=c.success&&c.data?c.data as typeof counts:null;if(countData&&countData.enrollment_count>0){const latest=await readContract("get_enrollment",[BigInt(countData.enrollment_count-1)]);if(latest.success&&latest.data)setLatestEnrollment(latest.data as Enrollment)}}finally{setIsRefreshing(false)}},[activeAddress]);
 useEffect(()=>{fetchState()},[fetchState]);const connect=async()=>{const r=await connectWallet();if(r.success&&typeof r.data==="string"){setAccount(r.data);fetchState()}};const gen=formatGen;
 return <div className="min-h-screen bg-white"><Header account={account} onConnectWallet={connect} onRefresh={fetchState} isRefreshing={isRefreshing}/><main>
  <section className="hero-wrap"><div className="hero-glow"/><div className="hero-orb hero-orb-left"/><div className="hero-orb hero-orb-right"/><div className="site-shell relative z-10"><p className="eyebrow">Course delivery escrow · powered by GenLayer</p><h1 className="hero-title">Tuition that follows delivery.</h1><p className="hero-copy">Lock course promises before enrollment. Let public evidence and decentralized AI consensus decide whether tuition is released, split, or refunded.</p><div className="hero-actions"><Link href="/offerings" className="btn-academic btn-glow">Browse offerings <ArrowRight size={19}/></Link><Link href="/create" className="btn-secondary" style={{minWidth:196}}>Publish a course</Link></div></div></section>
  <section className="product-stage site-shell"><div className="app-frame"><div className="app-bar"><div className="flex items-center gap-3"><div className="app-dots"><i/><i/><i/></div><strong className="text-sm">SyllabusBond ledger</strong></div><Link href="/verify" className="text-xs font-semibold text-violet-700">Verify totals →</Link></div><div className="ledger-grid"><aside className="ledger-side"><p className="eyebrow">Live protocol</p><h2 className="text-3xl font-semibold tracking-[-.04em] mt-3">Escrow at a glance.</h2><p className="text-sm text-[#73707b] leading-relaxed mt-4">On-chain custody and settlement totals from the active GenLayer contract.</p><div className="mt-8 space-y-3 text-sm"><div className="flex items-center gap-2"><Check size={16} className="text-emerald-600"/> {counts.offering_count} offerings published</div><div className="flex items-center gap-2"><Check size={16} className="text-emerald-600"/> {counts.enrollment_count} protected enrollments</div></div></aside><div className="ledger-main"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold">Value conservation</p><p className="text-xs text-[#85828c] mt-1">Received = held + paid + refunded</p></div><span className={`badge-academic ${syncOk?"badge-verified":"badge-pending"}`}>{syncOk?"State synced":"Sync unavailable"}</span></div><div className="metric-grid"><div className="metric-card"><span className="metric-label">Total received</span><span className="metric-value">{gen(totals.total_received)}</span></div><div className="metric-card"><span className="metric-label text-violet-700">Held in escrow</span><span className="metric-value text-violet-700">{gen(totals.total_held)}</span></div><div className="metric-card"><span className="metric-label text-emerald-700">Paid to organizers</span><span className="metric-value text-emerald-700">{gen(totals.total_paid_to_organizers)}</span></div><div className="metric-card"><span className="metric-label">Student refunds</span><span className="metric-value">{gen(totals.total_refunded_to_students)}</span></div></div></div></div></div></section>
  <section className="dark-section" id="how-it-works"><div className="site-shell"><div className="section-head"><span className="dark-kicker">HOW IT WORKS</span><h2 className="section-title">One promise. One escrow. A verifiable outcome.</h2><p className="section-copy">SyllabusBond turns a course description into locked terms, opens a fair evidence window, and lets GenLayer settle the enrollment.</p></div><div className="consensus-card"><div><p className="text-xs font-bold tracking-[.12em] text-[#d7a6ff] mb-5">SEMANTIC CONSENSUS</p><h3>Evidence meets the syllabus.</h3><p>Organizer delivery packets and student dispute evidence are compared with commitments locked before funding. The jury selects a closed outcome; the contract computes the payout.</p><Link href="/workspace" className="inline-flex items-center gap-2 mt-7 text-sm font-semibold text-white">Open a workspace <ArrowRight size={17}/></Link></div><div className="orbit"><div className="orbit-ring"/><div className="orbit-ring small"/><div className="orbit-core"><Scale size={31}/></div><div className="orbit-node n1"><FileCheck2 size={17}/></div><div className="orbit-node n2">50/50</div><div className="orbit-node n3"><ShieldCheck size={17}/></div><div className="orbit-node n4">AI</div></div></div>{latestEnrollment&&<div className="live-proof"><span>LIVE CONTRACT PROOF</span><strong>Enrollment #{latestEnrollment.id} · {latestEnrollment.status} · {latestEnrollment.decision}</strong><p>{latestEnrollment.reason}</p></div>}<div className="feature-row"><article className="dark-feature"><span>01 · COMMIT</span><h4>Terms locked first.</h4><p>Schedule, instructor, duration, syllabus and recovery rules are committed before student funds enter escrow.</p></article><article className="dark-feature"><span>02 · REVIEW</span><h4>Both sides can respond.</h4><p>Delivery evidence opens a challenge window so no interested party can force an immediate favorable judgment.</p></article><article className="dark-feature"><span>03 · SETTLE</span><h4>Payouts stay deterministic.</h4><p>Delivered pays the organizer, material reduction splits tuition, and non-delivery refunds the student.</p></article></div></div></section>
 </main><footer className="py-10 bg-black text-[#817e87] text-xs"><div className="site-shell flex flex-wrap justify-between gap-4"><span className="text-white font-semibold">SyllabusBond</span><span>GenLayer Studionet · LIVE CONTRACT</span></div></footer></div>
}
